### ISSUE TITLE
Feedbackc milestone 1

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/Crime_population#6]
Good job overall!

- Make sure you check the text for spelling and grammatical errors (particularly verb tense) before submitting.
- Good use of arrows to indicate functions in the app. Consider using checkboxes instead of radio buttons to allow for the selection of more than one crime type (and maybe add the second one with a dotted line. Alternatively, it could be interesting to select more than two cities.
- Since the two section of the landing page don't interact with each other, it could be a good idea to employ a tabbed interface so that there is not too much clutter on the main page. Maybe having the line graph in the first tab since it is more eye-catching than the table.
- Is the lower plot always crimes rate / 100k population or does it depend on the radio button in the upper section?

**Comment by huijuechen** [comment]
Thanks for the feedback. Comment on 2, 3, 4:
2. we are now allowing selection for more than two cities
3. a tabbed interface is now implemented, but more for the first panel, as tabs are now allowing switching between barplot and datatable
4. The lower plot always do crime rate per 100k comparison, since we feel like it doesnt make much sense to use lineplot to compare total crimes across cities, as some might be too big (cities with big population) while others being too small, putting them on the same graph would neglect the change on the small one. But you are right, that should be specified on the panel, we would add it.

**Comment by K3ra-y** [comment]
@joelostblom 
Thank you for the feedback. Please see below for addressed issue points.

1st point: Solved c0076ccfaf68b417a47de4fb6437234eed755078
2nd point: Solved edf531feeaee5e6c9d6ea655522a942da901bd8c
4th point: Solved 00f85ea79e6ac32f90b473766ce75dee6cb65424

**Comment by K3ra-y** [comment]
I believe we have not addressed the 3rd point, since it is not working yet.

**Comment by K3ra-y** [comment]
3rd point: Solved be4551c2299f622f19023ddd8241bec5398c1b07
